#pragma once
#define WIN32_LEAN_AND_MEAN
// Standard Libaries
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <string>
#include <xstring>
#include <vector>
#include <mutex>
#include <map>
#include <algorithm>
#include <io.h>
#include <fcntl.h>
// Dependencies
#include <Windows.h>
#include <detours.h>
#include <logging.h>
#include <helpers.h>
#include <sigscan.h>